# roles/mariadb/tasks/main.yml
---
- name: Add MariaDB repository
  become: yes
  ansible.builtin.yum_repository:
    name: mariadb_repo
    description: MariaDB 10.8
    enabled: yes
    baseurl: https://rpm.mariadb.org/10.11/rhel/$releasever/$basearch
    gpgkey: https://rpm.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
- name: Install MariaDB from Repo
  become: yes
  ansible.builtin.dnf:
    name: mariadb-server >= 10.11
    enablerepo: mariadb_repo
    state: present
- name: DB Configuration
  become: yes
  template:
    src: etc_my.cnf.d_custom.cnf.j2
    dest: /etc/my.cnf.d/custom.cnf
    mode: '0644'
- name: Start and Enable MariaDB
  become: yes
  ansible.builtin.systemd_service:
    name: mariadb
    enabled: true
    state: started
- name: Open MariaDB Port
  become: yes
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled
    immediate: true